name: 'IIS Site Status'

description: 'This action gets the status of an On-Prem IIS website'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  website-name:
    description: 'The name of the website to perform action on'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true

outputs:
  website-status:
    description: 'The status of the website'
    value: ${{ steps.action.outputs.website-status }}

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String "${{ inputs.service-account-password }}" -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -server '${{ inputs.server }}' `
          -website_name '${{ inputs.website-name }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password
